#!/usr/bin/env node
// ============================================================
// Glow DS — Token Compliance Validator
//
// Scans .tsx/.ts files for hardcoded values that should use
// DS tokens. Reports violations with suggested token replacements.
//
// Usage:
//   node scripts/validate-tokens.cjs [path]         # scan a file or directory
//   node scripts/validate-tokens.cjs --changed-only  # scan git-changed .tsx files
//
// Exit codes: 0 = clean, 1 = violations found
// ============================================================

const fs = require('fs')
const path = require('path')

// ── Hex color → semantic token reverse map ──────────────────
// Auto-generated by scripts/generate-hex-map.cjs from tokens/semantic/colors.ts
// and tokens/primitive/colors.ts. Regenerate via `npm run prebuild`.
const HEX_MAP_PATH = path.join(__dirname, 'generated', 'hex-to-token.json')
let HEX_TO_TOKEN = {}
try {
  HEX_TO_TOKEN = JSON.parse(fs.readFileSync(HEX_MAP_PATH, 'utf-8'))
} catch (err) {
  console.error(
    `⚠️  Hex map not found at ${path.relative(process.cwd(), HEX_MAP_PATH)}.\n` +
    `   Run: node scripts/generate-hex-map.cjs\n` +
    `   Unknown colors will be flagged generically until the map is generated.`
  )
}

// ── Spacing value → token map ──────────────────────────────
const PX_TO_SPACING = {
  4: 'semanticSpacing.xxxs', 8: 'semanticSpacing.xxs', 12: 'semanticSpacing.xs',
  16: 'semanticSpacing.s', 20: 'semanticSpacing.m', 24: 'semanticSpacing.l',
  32: 'semanticSpacing.xl', 40: 'semanticSpacing.xxl', 48: 'semanticSpacing.xxxl',
  56: 'semanticSpacing.xxxxl', 72: "semanticSpacing['5xl']",
}

// ── Radii value → token map ─────────────────────────────────
const PX_TO_RADII = {
  4: 'semanticRadii.xxxs', 8: 'semanticRadii.xxs', 12: 'semanticRadii.xs',
  16: 'semanticRadii.sn', 20: 'semanticRadii.m', 24: 'semanticRadii.ln',
  32: 'semanticRadii.xl', 40: 'semanticRadii.xxl', 48: 'semanticRadii.xxxl',
  999: 'semanticRadii.full',
}

// ── Excluded paths ──────────────────────────────────────────
const EXCLUDED_DIRS = [
  'tokens/primitive',
  'tokens/semantic',
  'lib/tailwind-preset',
  'node_modules',
  'dist',
  'scripts/',
  'Icon/icons/',         // SVG icon components legitimately contain hex fills
]

// ── Patterns ────────────────────────────────────────────────
const HEX_REGEX = /#([0-9a-fA-F]{3,8})\b/g
const INLINE_SVG_REGEX = /<svg[\s>]/gi

// Style property names that commonly hold spacing/size values
const STYLE_PROP_REGEX = /(?:padding|margin|gap|top|bottom|left|right|width|height|minWidth|minHeight|maxWidth|maxHeight|borderRadius|fontSize|lineHeight)\s*[:=]\s*(\d+)/g

// ── Helpers ─────────────────────────────────────────────────
function isExcluded(filePath) {
  const rel = path.relative(process.cwd(), filePath)
  return EXCLUDED_DIRS.some(d => rel.includes(d))
}

function isTokenConstantBlock(line, prevLines) {
  // Lines that define token constants (e.g., `const X = sc.primary...`) are OK
  if (/const\s+\w+\s*=\s*(sc\.|semanticColors|semanticSpacing|semanticRadii|typographyStyles|primitiveColors|primitiveShadows)/.test(line)) return true
  // Comments showing the hex value next to a token reference are OK
  if (/\/\/.*#[0-9a-fA-F]/.test(line)) return true
  return false
}

function isGlowIgnored(line) {
  // Require `glow-ignore:` followed by at least one non-whitespace character (a reason).
  // Documented in CLAUDE.md → "Escape Hatch: glow-ignore".
  return /glow-ignore:\s*\S+/.test(line)
}

function normalizeHex(hex) {
  hex = hex.toLowerCase()
  // Expand 3-char hex: #abc → #aabbcc
  if (hex.length === 4) {
    hex = '#' + hex[1] + hex[1] + hex[2] + hex[2] + hex[3] + hex[3]
  }
  return hex
}

// ── Scan a single file ──────────────────────────────────────
function scanFile(filePath) {
  const violations = []
  const content = fs.readFileSync(filePath, 'utf-8')
  const lines = content.split('\n')
  const rel = path.relative(process.cwd(), filePath)

  lines.forEach((line, idx) => {
    const lineNum = idx + 1

    // Skip glow-ignore lines
    if (isGlowIgnored(line)) return

    // Skip token constant definitions and comments
    if (isTokenConstantBlock(line, lines.slice(Math.max(0, idx - 2), idx))) return

    // Skip import lines
    if (/^\s*import\s/.test(line)) return

    // ── Check hardcoded hex colors ────────────────────────
    let match
    HEX_REGEX.lastIndex = 0
    while ((match = HEX_REGEX.exec(line)) !== null) {
      const hex = normalizeHex(match[0])
      // Skip rgba patterns (they're in the string, not bare hex)
      if (/rgba?\(/.test(line.slice(Math.max(0, match.index - 10), match.index))) continue
      // Skip hex in URL strings (image URLs)
      if (/['"`]https?:\/\//.test(line)) continue
      // Skip hex in keyframe/animation strings
      if (/url\(/.test(line)) continue

      const suggestion = HEX_TO_TOKEN[hex]
      if (suggestion) {
        violations.push({
          file: rel, line: lineNum, type: 'hardcoded-color',
          value: hex, suggestion: `Use ${suggestion} instead of ${hex}`,
        })
      } else if (hex.length === 7 || hex.length === 9) {
        // Unknown hex color — might be a new/unlisted color
        violations.push({
          file: rel, line: lineNum, type: 'unknown-color',
          value: hex, suggestion: `No matching DS token for ${hex} — check if this color should be added to the palette`,
        })
      }
    }

    // ── Check inline SVG ──────────────────────────────────
    INLINE_SVG_REGEX.lastIndex = 0
    if (INLINE_SVG_REGEX.test(line)) {
      // Allow inline SVG in two contexts:
      //   1. Icon definition files (Icon/icons/line/Search.tsx etc.) — the SVG *is* the icon
      //   2. DS component internals (src/components/Button/Button.tsx etc.) — animation primitives
      //      like loading spinners. Product code still gets flagged.
      const isIconFile = rel.includes('Icon/icons/')
      const isDsComponentInternal = rel.includes('src/components/')
      if (!isIconFile && !isDsComponentInternal) {
        violations.push({
          file: rel, line: lineNum, type: 'inline-svg',
          value: '<svg>', suggestion: 'Import from DS icon library: import XyzLine from "@/components/Icon/icons/line/Xyz"',
        })
      }
    }
  })

  return violations
}

// ── Collect files ───────────────────────────────────────────
function collectFiles(targetPath) {
  const stat = fs.statSync(targetPath)
  if (stat.isFile()) {
    if (/\.(tsx?|jsx?)$/.test(targetPath)) return [targetPath]
    return []
  }
  if (stat.isDirectory()) {
    const results = []
    const entries = fs.readdirSync(targetPath, { withFileTypes: true })
    for (const entry of entries) {
      const full = path.join(targetPath, entry.name)
      if (entry.isDirectory() && !['node_modules', 'dist', '.git'].includes(entry.name)) {
        results.push(...collectFiles(full))
      } else if (entry.isFile() && /\.(tsx?|jsx?)$/.test(entry.name)) {
        results.push(full)
      }
    }
    return results
  }
  return []
}

// ── Get git-changed files ───────────────────────────────────
function getChangedFiles() {
  const { execSync } = require('child_process')
  try {
    const output = execSync('git diff --name-only HEAD', { encoding: 'utf-8' })
    return output.trim().split('\n')
      .filter(f => /\.(tsx?|jsx?)$/.test(f))
      .map(f => path.resolve(process.cwd(), f))
      .filter(f => fs.existsSync(f))
  } catch {
    return []
  }
}

// ── Main ────────────────────────────────────────────────────
function main() {
  const args = process.argv.slice(2)
  let files = []

  if (args.includes('--changed-only')) {
    files = getChangedFiles()
    if (files.length === 0) {
      console.log('✅ No changed files to validate.')
      process.exit(0)
    }
  } else {
    const target = args[0] || 'src/components'
    files = collectFiles(path.resolve(process.cwd(), target))
  }

  // Filter excluded paths
  files = files.filter(f => !isExcluded(f))

  let allViolations = []

  for (const file of files) {
    const violations = scanFile(file)
    allViolations.push(...violations)
  }

  // ── Report ──────────────────────────────────────────────
  if (allViolations.length === 0) {
    console.log(`✅ Token compliance: ${files.length} files scanned, 0 violations.`)
    process.exit(0)
  }

  console.log(`\n⚠️  Token compliance: ${allViolations.length} violation(s) in ${files.length} files:\n`)

  // Group by file
  const byFile = {}
  for (const v of allViolations) {
    if (!byFile[v.file]) byFile[v.file] = []
    byFile[v.file].push(v)
  }

  for (const [file, violations] of Object.entries(byFile)) {
    console.log(`  📄 ${file}`)
    for (const v of violations) {
      const icon = v.type === 'hardcoded-color' ? '🎨' : v.type === 'inline-svg' ? '🖼️' : '❓'
      console.log(`     ${icon} Line ${v.line}: ${v.suggestion}`)
    }
    console.log()
  }

  process.exit(1)
}

main()
